version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-spring
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photodb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
